services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: sifre123
      POSTGRES_DB: gamepm_db
      POSTGRES_USER: gamepm_admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: